MODEL_2D:
  TYPE: "UNetResNet34"
  NUM_CLASSES: 6
  DUAL_HEAD: True
MODEL_3D:
  TYPE: "SCN"
  NUM_CLASSES: 6
  DUAL_HEAD: True
DATASET_SOURCE:
  TYPE: "NuScenesLidarSegSCN"
  TRAIN: ("train_day",)
  NuScenesLidarSegSCN:
    preprocess_dir: "/Labs/Scripts/3DPC/Datasets/3DPC/nuScenes_preprocess/nuScenes_lidarseg/preprocess"
    nuscenes_dir: "/Labs/Scripts/3DPC/Datasets/3DPC/nuScenes"  # only front cam images are needed
DATASET_TARGET:
  TYPE: "NuScenesLidarSegSCN"
  TRAIN: ("train_night",)
  VAL: ("val_night",)
  TEST: ("test_night",)
  NuScenesLidarSegSCN:
    preprocess_dir: "/Labs/Scripts/3DPC/Datasets/3DPC/nuScenes_preprocess/nuScenes_lidarseg/preprocess"
    nuscenes_dir: "/Labs/Scripts/3DPC/Datasets/3DPC/nuScenes"  # only front cam images are needed
    pselab_paths: ("/Labs/Scripts/3DPC/VFMSeg/out/nuscenes_lidarseg/day_night/uda/xmuda_pl/pselab_data/train_night.npy",)
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS: [1.97516268, 1., 2.10103946, 2.05838738, 1.53985452, 1.54031246]
  XMUDA:
    lambda_xm_src: 1.0
    lambda_xm_trg: 0.1
    lambda_pl: 1.0
VAL:
  BATCH_SIZE: 32
  PERIOD: 5000
OUTPUT_DIR: "/Labs/Scripts/3DPC/VFMSeg/out/@" #OUTPUT_DIR: "path/to/output/directory/@"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/xmuda