MODEL_2D:
  TYPE: "UNetResNet34"
  DUAL_HEAD: True
  NUM_CLASSES: 6
MODEL_3D:
  TYPE: "SCN"
  DUAL_HEAD: True
  NUM_CLASSES: 6
DATASET_SOURCE:
  TYPE: "VirtualKITTISCN"
  TRAIN: ("train",)
  VirtualKITTISCN:
    preprocess_dir: "/Labs/Scripts/3DPC/Datasets/3DPC/nuScenes_preprocess/virtual_kitti_preprocess/preprocess"
    virtual_kitti_dir: "/Labs/Scripts/3DPC/Datasets/3DPC/virtual_kitti"
    vfm_data_paths: "/Labs/Scripts/3DPC/Datasets/3DPC/XMUDA_WITH_VFM/virtual_kitti_preprocess_vfm/train"
DATASET_TARGET:
  TYPE: "SemanticKITTISCN"
  TRAIN: ("train",)
  VAL: ("val",)
  TEST: ("test",)
  SemanticKITTISCN:
    preprocess_dir: "/Labs/Scripts/3DPC/Datasets/3DPC/nuScenes_preprocess/semantickitti-preprocess/preprocess"
    semantic_kitti_dir: "/Labs/Scripts/3DPC/Datasets/3DPC/SKITTI/semantic_kitti"
    merge_classes_style: "VirtualKITTI"
    pselab_paths: ("/Labs/Scripts/3DPC/VFMSeg/out/virtual_kitti_semantic_kitti/xmuda_vfm_pl/pselab_data/train.npy",)
    vfm_data_paths: "/Labs/Scripts/3DPC/Datasets/3DPC/XMUDA_WITH_VFM/semantic_kitti_preprocess_vfm" # /train,  /test,  /val
DATALOADER:
  NUM_WORKERS: 5 #6 
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (25000, 28000)
  MAX_ITERATION: 30000
TRAIN:
  BATCH_SIZE: 8 
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 2000
  CLASS_WEIGHTS: [1., 2.03402089, 1.20641905, 2.21588055, 2.59745666, 1.82057006]
  XMUDA:
    lambda_xm_src: 0.1
    lambda_xm_trg: 0.01
    lambda_pl: 1.0
VAL:
  BATCH_SIZE: 8
  PERIOD: 2000
OUTPUT_DIR: "/Labs/Scripts/3DPC/VFMSeg/out/@" #OUTPUT_DIR: "path/to/output/directory/@"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/xmuda