MODEL_2D:
  TYPE: "UNetResNet34"
  NUM_CLASSES: 6
  DUAL_HEAD: True
MODEL_3D:
  TYPE: "SCN"
  NUM_CLASSES: 6
  DUAL_HEAD: True
DATASET_SOURCE:
  TYPE: "NuScenesLidarSegSCN"
  TRAIN: ("train_usa",)
  NuScenesLidarSegSCN:
    preprocess_dir: "/Labs/Scripts/3DPC/Datasets/3DPC/nuScenes_preprocess/nuScenes_lidarseg/preprocess"
    nuscenes_dir: "/Labs/Scripts/3DPC/Datasets/3DPC/nuScenes"  # only front cam images are needed
    vfm_data_paths: "/Labs/Scripts/3DPC/Datasets/3DPC/XMUDA_WITH_VFM/nuscene_preprocess_vfm/usa_singapore/resize/src/train"
DATASET_TARGET:
  TYPE: "NuScenesLidarSegSCN"
  TRAIN: ("train_singapore",)
  VAL: ("val_singapore",)
  TEST: ("test_singapore",)
  NuScenesLidarSegSCN:
    preprocess_dir: "/Labs/Scripts/3DPC/Datasets/3DPC/nuScenes_preprocess/nuScenes_lidarseg/preprocess"
    nuscenes_dir: "/Labs/Scripts/3DPC/Datasets/3DPC/nuScenes"  # only front cam images are needed
    pselab_paths: ("/Labs/Scripts/3DPC/VFMSeg/out/nuscenes_lidarseg/usa_singapore/xmuda_vfm_pl/pselab_data/train_singapore.npy",)
    vfm_data_paths: "/Labs/Scripts/3DPC/Datasets/3DPC/XMUDA_WITH_VFM/nuscene_preprocess_vfm/usa_singapore/resize/trg/train"
DATALOADER:
  NUM_WORKERS: 6 #4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS: [1.9241476, 1., 2.16763851, 2.78254323, 1.54875664, 1.85686537]
  XMUDA:
    lambda_xm_src: 1.0
    lambda_xm_trg: 0.1
    lambda_pl: 1.0
VAL:
  BATCH_SIZE: 32
  PERIOD: 5000
OUTPUT_DIR: "/Labs/Scripts/3DPC/VFMSeg/out/@"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/xmuda